booster:
  - gbtree
objective:
  - binary:logistic
n_estimators:
  - 100
  - 200
  - 400
  - 800
eta:
  _target_: scipy.stats.uniform
  loc: 0
  scale: 0.5
max_depth:
  _target_: scipy.stats.randint
  low: 3
  high: 60
subsample:
  _target_: scipy.stats.uniform
  loc: 0.5
  scale: 0.5
colsample_bytree:
  _target_: scipy.stats.uniform
  loc: 0.5
  scale: 0.5
lambda:
  _target_: scipy.stats.loguniform
  a: 1e-1
  b: 1e3
verbosity:
  - 0
enable_categorical:
  - True
random_state:
  - ${seed}
