defaults:
  - cv: repeated_stratified_kfold

_target_: sklearn.model_selection.RandomizedSearchCV
_partial_: true

scoring: accuracy
n_iter: 40
n_jobs: null
random_state: ${seed}
return_train_score: true
