defaults:
  - _self_
  - trainer: default
  - search_strategy: random_search_cv
  - param_distributions: xgboost
  - hydra: default
  - paths: default
  - wandb: default

# General configs
model_name: XGBoost
dataset_name: frequency-domain-features
project_name: fiesc-study-case
exp_number: "1"
task_name: Experiment-${exp_number}
run_name: ${model_name}-${dataset_name}
seed: 42

# Experiment configs
datafile: specialized_features.parquet
