name: Spectrum endpoint - FastAPI Docker Image Test

on:
  push:
    branches:
      - main

jobs:
  code-quality:
    name: Check coding standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry

      - name: Install Python dependencies
        run: poetry install --no-root

      - name: Check code formatting
        run: poetry run poe black-check
