spectrum:
  _target_: utils.features.frequency_domain.filter_spectrum
  _partial_: true

envelope:
  _target_: utils.signal_representations.filter_envelope
  _partial_: true

spectral_bands:
  [
    [5, 500],
    [500, 1000],
    [5, 1000],
    [500, 1500],
    [1000, 1500],
    [1500, 2000],
    [2000, 3000],
    [3000, 5000],
  ]

envelope_bands: [[5, 300], [250, 500], [450, 750], [700, 1050]]
